---
title: "Dots Reproducibility Test"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r}
library(data.table)
library(ggplot2)
# source("explore_functions.r")
```

# Cross-sessions comparison of dotsPositions.csv files
```{r}
file1 <- fread("/home/adrian/SingleCP_DotsReversal/DotsReproducibilityTest/raw/2019_09_25_13_47/2019_09_25_13_47_dotsPositions_truncated.csv")
file1[,`:=`(seqDumpTime=NULL,pilotID=NULL,taskID=NULL)]

file2 <- fread("/home/adrian/SingleCP_DotsReversal/DotsReproducibilityTest/raw/2019_09_25_13_53/2019_09_25_13_53_dotsPositions.csv")
file2[,`:=`(seqDumpTime=NULL,pilotID=NULL,taskID=NULL)]

file3 <- fread("/home/adrian/SingleCP_DotsReversal/DotsReproducibilityTest/raw/2019_09_27_11_29/2019_09_27_11_29_dotsPositions.csv")
file3[,`:=`(seqDumpTime=NULL,pilotID=NULL,taskID=NULL)]
```

```{r}
match <- file2[1:2392,]==file3
```

```{r}
colSums(match)
```


# Frame count variability
10 trials of 200msec, followed by 10 trials of 400msec were run, all with the same random seed.

```{r}
path_to_fira <- "/home/adrian/SingleCP_DotsReversal/DotsReproducibilityTest/raw/2019_09_23_14_49/2019_09_23_14_49_FIRA.csv"
path_to_dots <- "/home/adrian/SingleCP_DotsReversal/DotsReproducibilityTest/raw/2019_09_23_14_49/2019_09_23_14_49_dotsPositions.csv"
```

```{r}
fira <- fread(path_to_fira)
dots <- fread(path_to_dots)
```

```{r}
dots[,trial:=factor(seqDumpTime, ordered=T)]
dotsTrials <- length(levels(dots$trial))
if (dotsTrials == max(fira$trialIndex)) {
  levels(dots$trial) <- seq(dotsTrials)
}
```

```{r}
str(dots)
```

Are frames counted without holes?
```{r}
frames <- unique(dots[,.(frameIdx), by=trial])
frameCounts <- frames[,.(maxFrames=max(frameIdx), numFrames=.N), by=trial]
frameCounts[,type:='short']
frameCounts[trial>10,type:='long']
frameCounts[,type:=as.factor(type)]
```

```{r}
noholes<-prod(frameCounts$maxFrames == frameCounts$numFrames)
if (noholes) {print("no holes!")}
```

```{r}
frameCounts[,reltrial:=as.integer(seq(dotsTrials / 2)), by=type]
```

```{r, fig.width=10, fig.height=6}
# ggplot(frameCounts, aes(x=reltrial, y=numFrames, color=type)) + 
#   geom_point(size=4) +
#   scale_y_continuous(breaks = seq(10, 30, 1)) +
#   theme(text=element_text(size=20),
#         panel.grid.minor = element_blank(),
#         panel.grid.major = element_line(colour = "white",size=0.75))
```
# Dots position variability
On a single frame, each dot is represented by its (x.y) coordinates. Dots positions should be equal across trials, for a fixed frame number.
```{r}
dots_dt <- dots[isActive == 1, .(xpos, ypos, trial, frameIdx)]
dots_dt[,dotID:=seq(.N), by=.(trial, frameIdx)]
str(dots_dt)
```

```{r}
dots_melted <- melt(dots_dt, measure.vars=c("xpos", "ypos"), variable.name="axis", value.name="position", id.vars=c("trial", "frameIdx", "dotID"))
head(dots_melted)
```

```{r, fig.width=12, fig.height=30}
ggplot(dots_melted, aes(x=position, group=axis)) + geom_histogram(bins=500) + facet_grid(frameIdx~axis) + theme(text=element_text(size=20))
```

