---
title: "Data IO Fall 2019 Single CP task"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r}
library(data.table)
library(ggplot2)
source("process.r")
```

```{r}
DATA_FOLDER <- '/home/adrian/SingleCP_DotsReversal/Fall2019/raw/'
```

```{r}
#t1 <- fread(paste0(DATA_FOLDER, 'completed4AFCtrials_task99_date_2019_11_05_10_27.csv'))
full_data <- get_full_data(paste0(DATA_FOLDER, 'full_2019_11_22.csv'))
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

# Logistic Fits
```{r}
# ARGS:
#  subj         string for level of subject column
#  base_data    data.table with data from all subjects
logistic_plot <- function(subj, vd, base_data) {
  # fit logistic regression
  subj_base_data <- base_data[subject==subj]
  fitted <- glm(data = subj_base_data, formula = dirChoice ~ scoh, family = binomial(link = logit))
  pred_base <- data.table(scoh=seq(-100,100,10))
  pred_base[, `:=`(propRight=predict(fitted, newdata=pred_base, type="response"), 
                   subject=subj,
                   duration=vd)]
  
  # this is a data.table with only the proportion choose right data
  new_data <- subj_base_data[,.(propRight=sum(dirChoice=='right')/.N, numTrials=.N), by=.(scoh)]
  new_data[,`:=`(ci=1.96*sqrt(propRight*(1-propRight)/numTrials), 
                 subject=subj,
                 duration=vd)]
  
  tot_zeros = subj_base_data[scoh==0, .N]
  num_zero_right = subj_base_data[scoh==0 & direction=="right", .N]
  
  return(list(new_data, pred_base, round(num_zero_right/tot_zeros, 2)))
}

# 5*4 below is numSubjects * numVD
dt1 <- vector(mode = "list", length = 5*4)  # for choice proportion data
dt2 <- vector(mode = "list", length = 5*4)  # for fitted curves

counter <- 1
for (ss in c(10,11,12)) {
  for (vdur in c(100,200,250,300,400,600)) {
    s <- full_data[duration == vdur & presenceCP=="noCP"]
    s[direction == "left", scoh:=-coherence]
    s[direction == "right", scoh:=coherence]
    returned <- logistic_plot(ss, vdur, s)  
    dt1[counter] <- returned[1]
    dt2[counter] <- returned[2]
    counter <- counter + 1
  }
}

new_data <- rbindlist(dt1)
pred_base <- rbindlist(dt2)

new_data[, `:=`(duration=as.factor(duration), subject=as.factor(subject))]
pred_base[, `:=`(duration=as.factor(duration), subject=as.factor(subject))]

# plot
gp <- ggplot(new_data, aes(x=scoh, y=propRight)) + 
  theme_bw() + 
  geom_line(data=pred_base, size=1.3) + 
  geom_point(colour="brown1") + geom_errorbar(aes(ymin=propRight-ci, ymax=propRight+ci), colour="brown1", width=3) +
  geom_hline(yintercept = 0.5, linetype="dashed") + geom_vline(xintercept = 0, linetype="dashed") + 
  labs(title="Psychometric functions on noCP trials", subtitle = "pilot data from summer 2019") +
  theme(text=element_text(size=20), plot.title = element_text(hjust=0.5)) +
  facet_grid(subject~duration)
```

```{r, fig.width=12, fig.height=9}
plot(gp)
```


# Main Plots
## Direction Accuracy as function of VD
### All subjects 
```{r}
crossover <- full_data[coh_cat=="th",`:=`(dirAcc=sum(dirCorrect)/.N, numTrials=.N), by=.(coh_cat, duration, probCP)]
crossover[,`:=`(ci=1.96*sqrt(dirAcc * (1-dirAcc) / numTrials))]
pd <- position_dodge(5)
ggplot(unique(crossover[coh_cat=="th",.(dirAcc, duration, probCP, ci)]), 
       aes(x=duration, y=dirAcc, col=probCP)) + geom_point(size=2.3, position=pd) + geom_line(size=1.4) + 
  geom_errorbar(aes(ymin=dirAcc - ci, ymax=dirAcc+ci), width=10, position=pd) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  scale_color_manual(values=c(cbbPalette[8], cbbPalette[6])) +
  theme(text=element_text(size=17))
```

### Subject-by-subject
```{r}
crossover <- full_data[coh_cat=="th",`:=`(dirAcc=sum(dirCorrect)/.N, numTrials=.N), by=.(coh_cat, duration, probCP, subject)]
crossover[,`:=`(ci=1.96*sqrt(dirAcc * (1-dirAcc) / numTrials))]
pd <- position_dodge(5)
ggplot(unique(crossover[coh_cat=="th",.(dirAcc, duration, probCP, ci, subject)]), 
       aes(x=duration, y=dirAcc, col=probCP)) + geom_point(size=2.3, position=pd) + geom_line(size=1.4) + facet_wrap(~subject, ncol=2) +
  geom_errorbar(aes(ymin=dirAcc - ci, ymax=dirAcc+ci), width=10, position=pd) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  scale_color_manual(values=c(cbbPalette[8], cbbPalette[6])) +
  theme(text=element_text(size=17))
```
## Direction Accuracy as function of VD -- by presenceCP
### All subjects together
```{r, fig.width=7}
acc0 <- full_data[coh_cat=="th",`:=`(dirAcc=sum(dirCorrect)/.N, numTrials=.N), by=.(coh_cat, presenceCP, duration, probCP)]
acc0[,`:=`(ci=1.96*sqrt(dirAcc * (1-dirAcc) / numTrials))]
pd <- position_dodge(5)
ggplot(unique(acc0[coh_cat=="th",.(dirAcc, presenceCP, duration, probCP, ci)]), 
       aes(x=duration, y=dirAcc, col=presenceCP)) + geom_point(size=3.5, position=pd) + 
  geom_line(size=1.3) + 
  facet_grid(~probCP) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  geom_errorbar(aes(ymin=dirAcc - ci, ymax=dirAcc+ci), width=12, position=pd) +
  scale_color_manual(values=c(cbbPalette[4], cbbPalette[7]) , name = "", labels = c("no CP", "CP")) +
  theme(text=element_text(size=16))
```
### Subject-by-subject
```{r, fig.width=7, fig.height=8}
acc0 <- full_data[coh_cat=="th",`:=`(dirAcc=sum(dirCorrect)/.N, numTrials=.N), by=.(coh_cat, presenceCP, duration, probCP, subject)]
acc0[,`:=`(ci=1.96*sqrt(dirAcc * (1-dirAcc) / numTrials))]
pd <- position_dodge(5)
ggplot(unique(acc0[coh_cat=="th",.(dirAcc, presenceCP, duration, probCP, ci, subject)]), 
       aes(x=duration, y=dirAcc, col=presenceCP)) + geom_point(size=3.5, position=pd) + 
  geom_line(size=1.3) + 
  facet_grid(subject~probCP) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  geom_errorbar(aes(ymin=dirAcc - ci, ymax=dirAcc+ci), width=12, position=pd) +
  scale_color_manual(values=c(cbbPalette[4], cbbPalette[7]) , name = "", labels = c("no CP", "CP")) +
  theme(text=element_text(size=17))
```
```{r, fig.width=10}
acc <- full_data[coh_cat=="th",dirAcc:=sum(dirCorrect)/.N, by=.(coh_cat, presenceCP, duration, probCP, cpChoice)]
ggplot(unique(acc[coh_cat=="th",.(dirAcc, presenceCP, duration, probCP, cpChoice)]), 
       aes(x=duration, y=dirAcc, col=presenceCP)) + geom_point(size=2) + geom_line(size=1.5, aes(linetype=cpChoice)) + facet_grid(~probCP) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  scale_color_manual(values=c(cbbPalette[4], cbbPalette[7]) , name = "", labels = c("no CP", "CP")) +
  theme(text=element_text(size=17))
```

```{r, fig.width=10}
cpd <- full_data[,`:=`(cpAcc=sum(cpCorrect)/.N, numTrials=.N), by=.(coh_cat, duration, probCP)]
cpd[,`:=`(ci=1.96*sqrt(cpAcc * (1-cpAcc) / numTrials))]
pd <- position_dodge(.2)
ggplot(unique(cpd[,.(cpAcc, coh_cat, duration, probCP, ci)]), 
       aes(x=probCP, y=cpAcc, col=coh_cat, group=coh_cat)) + geom_point(size=5, position=pd) + geom_line(size=1) + facet_grid(~duration) +
   geom_hline(yintercept = c(0.5,1), linetype='dashed') +
  scale_color_manual(values=cbbPalette) + 
  geom_errorbar(aes(ymin=cpAcc - ci, ymax=cpAcc+ci), width=1, position=pd) +
  theme(text=element_text(size=17)) + ggtitle("Acc. at CP-detection")
```

```{r, fig.width=10}
d_modified <- full_data[coh_cat!="100"]
d_modified[, `:=`(respondedCP=0, isCP=0)]
d_modified[cpChoice == "CP", respondedCP:=1]
d_modified[presenceCP == "CP", isCP:=1]
dd <- d_modified[,.(isCP, respondedCP, subject, probCP, dirChoice, dirCorrect, cpCorrect, duration, coh_cat)]
roc_cpd_avg_subj <- unique(dd[,
                             .(propCP=sum(respondedCP)/.N, trueProp=sum(isCP)/.N, numTrials=.N),
                             by=.(probCP, duration, coh_cat)])
roc_cpd_avg_subj[, `:=`(ciPropCP=1.96*sqrt(propCP * (1-propCP) / numTrials), ciTrueProp=1.96*sqrt(trueProp * (1-trueProp) / numTrials))]

## Average across 5 subjects

ggplot(roc_cpd_avg_subj, aes(x=probCP, y=propCP, group=coh_cat, col=coh_cat)) +
 geom_point(size=4) +
 geom_line(size=1.5) +
 geom_line(aes(x=probCP, y=trueProp)) +
 geom_hline(yintercept = c(0.5,1), linetype='dashed') +
 geom_errorbar(aes(ymin=propCP-ciPropCP, ymax=propCP+ciPropCP), width=.3, size=.7) +
 scale_color_manual(values=cbbPalette) +
  facet_wrap(~duration, ncol=6) +
 # scale_color_brewer(palette = "Dark2") +
 theme_bw() +
 theme(text=element_text(size=17)) + 
  ggtitle("Proportion Report CP")
```
```{r}
get_dprime <- function(hits, fas) {
  return(qnorm(hits) - qnorm(fas))
}
```
```{r}
roc2 <- full_data[coh_cat=="th" & duration > 200,.(presenceCP, cpChoice, duration, probCP, coh_cat)]
roc2[presenceCP=="CP" & cpChoice == "noCP",cpd:="Miss"]
roc2[presenceCP == "CP" & cpChoice == "CP", cpd:="Hit"]
roc2[presenceCP == "noCP" & cpChoice == "CP", cpd:="FA"]
roc2[presenceCP == "noCP" & cpChoice == "noCP", cpd:="CR"]
roc2[,cpd:=factor(cpd, levels = c("Hit", "FA", "CR", "Miss"))]

roc2[cpd=="Miss" & presenceCP == "CP", `:=`(len=.N), by=.(duration, probCP)]
roc2[cpd=="CR" & presenceCP == "noCP", len:=.N, by=.(duration, probCP)]
roc2[cpd=="Hit" & presenceCP == "CP", len:=.N, by=.(duration, probCP)]
roc2[cpd=="FA" & presenceCP == "noCP", len:=.N, by=.(duration, probCP)]
roc2 <- unique(roc2[,`:=`(presenceCP=NULL, cpChoice=NULL)])
rocflat <- dcast(roc2, duration + probCP ~ cpd, value.var="len")
rocflat[,`:=`(totalCP=0L, totalNoCP=0L)]
rocflat[!is.na(Miss) & !is.na(Hit),`:=`(totalCP=Hit + Miss)]
rocflat[!is.na(FA) & !is.na(CR),`:=`(totalNoCP=CR + FA)]
rocflat[,Hit:=Hit/totalCP]
rocflat[,Miss:=Miss / totalCP]
rocflat[,CR:=CR / totalNoCP]
rocflat[,FA:=FA / totalNoCP]
rocflat[,total:=NULL]
rocflat[,dprime := get_dprime(Hit, FA)]

# histograms
roc3 <- melt(rocflat, measure.vars = c("Hit", "FA", "Miss", "CR"), variable.name = "cpd", value.name = "len")
# head(roc3)

ggplot(data=roc3, aes(x=probCP, y=len, fill=cpd)) +
  geom_bar(stat="identity", position=position_dodge()) +
  facet_grid(~duration) +
  theme_bw() +
  ylab("%") +
  ggtitle("CPD performance") +
  theme(text=element_text(size=18))
```

```{r}
ggplot(rocflat, aes(x=probCP, y=dprime)) + geom_point(size=4) + facet_grid(~duration) + 
  geom_hline(yintercept=0, linetype="dashed") +
  theme(text=element_text(size=18))
```


<!--
# Investigation of time variability
```{r}
# str(full_data)
```


```{r}
full_data[,trueVD:=1000*(dotsOff-dotsOn)]
```

```{r, fig.width=10, fig.height=5}
# ref: https://stackoverflow.com/a/34045068
# I have established that presenceCP is not the reason for bimodality of the histograms
# nor is the date of the experiment
ggplot(full_data, aes(x=trueVD, fill=cbbPalette[3])) + geom_histogram() + 
  facet_wrap(~factor(duration), scales="free") + theme_classic() +
  theme(text=element_text(size=17), legend.position="none") 
```

```{r}
ggplot(full_data, aes(x=finalCPTime)) + geom_histogram() + theme_bw() + theme(text=element_text(size=17)) 
```
-->
