---
title: "Effect of pre-CP stimulus on 100-msec post-CP accuracy"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r}
library(ggplot2)
library(data.table)
source("explore_functions.r")
```

```{r}
data <- get_full_data()
```

```{r}
names(data)
```

```{r, fig.width=10,fig.height=15}
subdata <- data[(viewingDuration == 100 | viewingDuration == 300) & coh_cat == "th",
                .(dirCorrect, subject, probCP, presenceCP, viewingDuration)]
subdata[, `:=`(accuracy=mean(dirCorrect), vv=mean(dirCorrect)*(1-mean(dirCorrect))/.N),
        by=.(viewingDuration, subject, probCP, presenceCP)]
tocast <- unique(subdata[,dirCorrect:=NULL])
wide <- dcast(tocast,
              subject + probCP + presenceCP ~ viewingDuration, value.var = c("accuracy", "vv"))

for (subj in c("S1", "S2", "S3", "S4", "S5")) {
  for (pcp in c("0", "0.2", "0.5", "0.8")) {
  wide[subject == subj & probCP == pcp & presenceCP == "CP",
       accuracy_100 := wide[subject == subj & probCP == pcp & presenceCP == "noCP", accuracy_100]]
  wide[subject == subj & probCP == pcp & presenceCP == "CP",
       vv_100 := wide[subject == subj & probCP == pcp & presenceCP == "noCP", vv_100]]
  }
}

wide[,`:=`(accDiff=accuracy_300 - accuracy_100,ci=1.96*sqrt(vv_100+vv_300))]


ggplot(wide, aes(x=presenceCP, y=accDiff)) +
  geom_point(size=3.7) +
  geom_line(aes(group=interaction(probCP, subject)), size=1.5) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_errorbar(aes(ymin=accDiff - ci, ymax=accDiff + ci), width=.1, size=1) +
  facet_grid(subject~probCP) + theme(text=element_text(size=20)) + ylab("Acc(300) - Acc(100)") +
  labs(title="Effect of pre-CP stimulus on 100-msec post-CP accuracy", subtitle="threshold coherence")


```

