---
title: "Accuracy plots"
output: html_notebook
---

```{r}
library(data.table)
library(ggforce)
source("explore_functions.r")
```

```{r}
data <- get_full_data() 
```


Per-subject accuracy at threshold coherence on non-CP trials, as function of VD
```{r}
# to_plot <- data[
#   coherence > 0 & 
#     coherence < 100 &
#     presenceCP == "no-CP",
#   .(accuracy=mean(dirCorrect), numTrials=.N), 
#   by=.(subject, viewingDuration)
# ]
# to_plot[,se:=sqrt(accuracy * (1-accuracy) / numTrials)]
# to_plot[,ci:=1.96*se]
# print(to_plot[order(subject, viewingDuration)])
```

```{r, fig.width = 12, fig.height = 7.8}
# ggplot(aes(x=viewingDuration, y=accuracy, col=subject, group=subject), data=to_plot) + 
#   geom_line(size=1.5) + 
#   geom_point() +
#   geom_hline(yintercept=c(.5,.9), color="black") +
#   geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=.1) +
#   facet_wrap(~subject) +
#   theme(text = element_text(size=20))
```

Same as above, altogether.
```{r, fig.width = 12, fig.height = 7.8}
# pd <- position_dodge(20) # move them .05 to the left and right
# ggplot(aes(x=viewingDuration, y=accuracy, col=subject, group=subject), data=to_plot) + 
#   geom_line(size=1.2, position = pd) + 
#   geom_point(position=pd, size=3) +
#   geom_hline(yintercept=c(.5,.9), color="black") +
#   geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=30, position=pd, size=1) +
#   theme(text = element_text(size=20))
```


By Prob-CP
```{r}
nonQuestData <- data[block != "Quest"]
to_plot2 <- nonQuestData[
  coherence > 0 &
    coherence < 100 &
    presenceCP == "no-CP",
  .(accuracy=mean(dirCorrect), numTrials=.N),
  by=.(subject, viewingDuration, probCP)
]
to_plot2[,se:=sqrt(accuracy * (1-accuracy) / numTrials)]
to_plot2[,ci:=1.96*se]
```


```{r, fig.width = 20, fig.height = 18}
# ggplot(aes(x=viewingDuration, y=accuracy, col=subject), data=to_plot2) + 
#   geom_line(size=1.5) + 
#   geom_point() +
#   geom_hline(yintercept=c(.5,.9), color="black") +
#   geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=.1) +
#   facet_grid(subject~probCP) +
#   theme(text = element_text(size=20))
```



Accuracy (DD) on non-CP trials as a function of coherence, for fixed viewing duration.
```{r}
factored_threshold <- nonQuestData[,coh_cat:="0"]
factored_threshold[coherence > 0, coh_cat:= "th"]
factored_threshold[coherence==100, coh_cat:="100"]
factored_threshold[,coh_cat:=factor(coh_cat, levels=c("0", "th", "100"), ordered=T)]

to_plot3 <- factored_threshold[
    presenceCP == "no-CP",
  .(accuracy=mean(dirCorrect), numTrials=.N),
  by=.(subject, viewingDuration, coh_cat)
]
to_plot3[,se:=sqrt(accuracy * (1-accuracy) / numTrials)]
to_plot3[,ci:=1.96*se]
```

```{r, fig.height=9, fig.width=12}
# ggplot(aes(x=coh_cat, y=accuracy, col=subject), data=to_plot3) +
#   geom_point() +
#   geom_hline(yintercept=c(.5,1), color="black") +
#   geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=.1) +
#   facet_grid(subject~viewingDuration) +
#   theme(text = element_text(size=20))
```


Accuracy at 100 & 200 msec for fixed coh is invariant across all ProbCP conditions
```{r}
to_plot4 <- factored_threshold[
  viewingDuration < 250 &
    coh_cat == "th",
  .(accuracy=mean(dirCorrect), numTrials=.N),
  by=.(subject, viewingDuration, probCP)
]
to_plot4[,se:=sqrt(accuracy * (1-accuracy) / numTrials)]
to_plot4[,ci:=1.96*se]
```

```{r}
# ggplot(aes(x=probCP, y=accuracy, col=subject), data=to_plot4) +
#   geom_point() +
#   geom_line(group=1) +
#   geom_hline(yintercept=c(.5,1), color="black") +
#   geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=.1) +
#   facet_grid(subject~viewingDuration) +
#   theme(text = element_text(size=20))
```

Per prob-CP condition, accuracy at 200 msec ishigher than at 300 msecon CP trials.
```{r}
to_plot5 <- factored_threshold[
  ((viewingDuration == 200) | (viewingDuration == 300 & presenceCP == "CP")) &
    coh_cat=="th",
  .(accuracy=mean(dirCorrect), numTrials=.N), 
  by=.(presenceCP, subject, viewingDuration, probCP)
]
to_plot5[,se:=sqrt(accuracy * (1-accuracy) / numTrials)]
to_plot5[,ci:=1.96*se]
```

```{r}
str(to_plot5)
```

```{r}
ggplot(to_plot5, aes(x=factor(viewingDuration), y=accuracy, col=presenceCP)) + 
  geom_point() +
  geom_hline(yintercept=c(.5,1), color="black", linetype="dashed") +
  geom_errorbar(aes(ymin=accuracy-ci, ymax=accuracy+ci), width=.1) +
  facet_grid(subject~probCP) +
  scale_color_brewer(palette="Dark2")
```

