---
title: "Simulations Psychophysics Single Change Point"
author: Adrian Radillo
output: html_notebook
---

<!-- cheat sheet
 executing chunk *Ctrl+Shift+Enter*. 
 Add new chunk *Ctrl+Alt+I*.
 press *Ctrl+Shift+K* to preview the HTML file.
-->
```{r}
# load required libraries for the notebook
library('sde')
library('fBasics')
library('ggplot2')
library('reshape2')
rm(list=ls()) # clear existing vars in environment
```

# Produce trajectories for various models
## Normative model
```{r}
#Set up parameters
d0<- 1 # drift magnitude
s0<- 1 # stdev magnitude
cp <- 0.5 # change point time

viewing_duration <- 1;

num_traj=500;
num_time_points=500;
t <- 0:num_time_points  # time
dt <- 1/num_time_points # time step in sec
tt <- dt * t # in sec
cp_idx <- floor(num_time_points/2)
```

```{r}
#Simulate 'num_traj' trajectories from the normative model
s <- expression(s0)
d <- expression(d0*(Heaviside(-t,-cp)-Heaviside(t,cp))-2*sinh(x))
sde.sim(t0 = 0, T = viewing_duration, X0 = 0, N = num_time_points, drift=d,
        sigma=s, sigma.x=0, method = "euler",M=num_traj) -> normModel
```

## Linear-leak model
```{r}
#Simulate 'num_traj' trajectories from the linear-leak model
linLeak <- 4
d <- expression(d0*(Heaviside(-t,-cp)-Heaviside(t,cp))-linLeak*x)
sde.sim(t0 = 0, T = viewing_duration, X0 = 0, N = num_time_points, drift=d,
        sigma=s, sigma.x=0, method = "euler",M=num_traj) -> linModel
```

# Comparison of mean trajectories between the two models
```{r}
# get mean trajectories
meanNorm <- rowMeans(normModel)
meanLin <- rowMeans(linModel)
means_df <- data.frame("time" = tt, 
                "normModel" = meanNorm,
                "linModel" = meanLin)
head(means_df)
```

```{r}
# plotting script
options(scipen=999)
theme_set(theme_bw())

# Load data (to be developed) ------------------------------------------
X <- melt(means_df,id=c("time"))
head(X)
colnames(X)[2] <- "model"
cp_time=0.5

# Add plot components --------------------------------
gg <- ggplot(X, aes(x=time, y=value)) + 
  geom_line(aes(col=model), size=1.5) + 
  geom_vline(xintercept = cp_time, linetype="dashed", 
             color = "blue", size=1.5) +
  geom_hline(yintercept = 0, color="black")+
  xlim(c(0, 1)) + #ylim(c(-1, 1)) + 
  labs(title="Mean Trajectories", y="evidence", x="time",subtitle="1,000 realizations")

# Modify theme components -------------------------------------------
bf <- 20
sf <- 17
gg + theme(plot.title=element_text(size=bf, 
                                   face="bold", 
                                   lineheight=1.2),  # title
           plot.subtitle=element_text(size=sf-3, 
                                      family="American Typewriter"),  # subtitle
           plot.caption=element_text(size=sf),  # caption
           axis.title.x=element_text(size=(sf+2)),  # X axis title
           axis.title.y=element_text(size=(sf+2)),  # Y axis title
           axis.text.x=element_text(size=sf),  # X axis text
           axis.text.y=element_text(size=sf), # Y axis text
           legend.title = element_text(size=sf, color = "firebrick"),
           legend.text = element_text(size=sf-2),
           panel.grid.minor = element_blank()) # remove minor grid
```

# Comparison of accuracy profiles between the two models
```{r}
pos <- normModel>0
neg <- normModel<=0
spos<-rowSums(pos)
sneg<-rowSums(neg)
accNorm <- c(spos[1:cp_idx],sneg[(cp_idx+1):(num_time_points+1)]) / num_traj

pos <- linModel>0
neg <- linModel<=0
spos<-rowSums(pos)
sneg<-rowSums(neg)
accLin <- c(spos[1:cp_idx],sneg[(cp_idx+1):(num_time_points+1)]) / num_traj
```

```{r}
# plot commands
accuracy_df <- data.frame("time" = tt, 
                 "normModel" = accNorm,
                 "linModel" = accLin)
#write.csv(df,"acc_means.csv")

df <- melt(accuracy_df,id=c("time"))
colnames(df)[2] <- "model"
cp_time=0.5

# Add plot components --------------------------------
gg <- ggplot(df, aes(x=time, y=value)) + 
  geom_line(aes(col=model), size=1.5) + 
  geom_vline(xintercept = cp_time, linetype="dashed", 
             color = "blue", size=1.5) +
  geom_hline(yintercept = 0, color="black")+
  xlim(c(0.0001, 1)) + ylim(c(0, 1)) + 
  labs(title="Accuracy", y="% correct", x="time",subtitle="1,000 realizations")

# Modify theme components -------------------------------------------
bf <- 20
sf <- 17
gg + theme(plot.title=element_text(size=bf, 
                                   face="bold", 
                                   lineheight=1.2),  # title
           plot.subtitle=element_text(size=sf-3, 
                                      family="American Typewriter"),  # subtitle
           plot.caption=element_text(size=sf),  # caption
           axis.title.x=element_text(size=(sf+2)),  # X axis title
           axis.title.y=element_text(size=(sf+2)),  # Y axis title
           axis.text.x=element_text(size=sf),  # X axis text
           axis.text.y=element_text(size=sf), # Y axis text
           legend.title = element_text(size=sf, color = "firebrick"),
           legend.text = element_text(size=sf-2),
           panel.grid.minor = element_blank()) # remove minor grid
```

