---
title: "Integration around CP"
output:
  html_document:
    df_print: paged
    code_folding: hide
---
```{r}
library(data.table)
library(ggplot2)
source("explore_functions.r")
```

```{r}
data <- get_full_data()
data[,`:=`(acc=mean(dirCorrect),
           vv=mean(dirCorrect)*(1-mean(dirCorrect))/.N),
     by=.(viewingDuration, subject, probCP, presenceCP, coh_cat)]
tocast <- unique(data[(viewingDuration == 200 | viewingDuration == 300) & coh_cat == "th", 
                      .(acc, subject, probCP, presenceCP, viewingDuration, vv)])
```

```{r}
wide <- dcast(tocast, 
              subject + probCP + presenceCP ~ viewingDuration, value.var = c("acc", "vv"))
```

```{r}
# head(tocast)

# fill NA values for vd200 at CP trials to vd200 at noCP trials
for (subj in c("S1", "S2", "S3", "S4", "S5")) {
  for (pcp in c("0", "0.2", "0.5", "0.8")) {
  wide[subject == subj & probCP == pcp & presenceCP == "CP", 
       acc_200 := wide[subject == subj & probCP == pcp & presenceCP == "noCP", acc_200]]
  wide[subject == subj & probCP == pcp & presenceCP == "CP", 
       vv_200 := wide[subject == subj & probCP == pcp & presenceCP == "noCP", vv_200]]
  }
}

wide[,`:=`(accDiff=acc_300 - acc_200,ci=1.96*sqrt(vv_200+vv_300))]
```

```{r, fig.width=10, fig.height=10}
ggplot(wide, aes(x=presenceCP, y=accDiff)) + geom_point() + geom_line(aes(group=interaction(probCP, subject))) +
  geom_hline(yintercept = 0) + geom_errorbar(aes(ymin=accDiff - ci, ymax=accDiff + ci), width=.1) +
  facet_grid(subject~probCP) + theme(text=element_text(size=20)) + ylab("Acc(300) - Acc(200)") + ggtitle("Accuracy difference around CP")
```

